name: New Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      # Post a comment on newly opened PRs describing the deployment process and related PR steps to deploy
      - name: new pull request
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/github-script@f05a81df23035049204b043b50c3322045ce7eb3 # pin@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commentBody = `\
            ### ðŸ‘‹ Thanks for opening a pull request!

            If you are new, please check out the trimmed down summary of our deployment process below:

            1. ðŸ‘€ Observe the CI jobs and tests to ensure they are passing
            1. âœ”ï¸ Obtain an approval/review on this pull request
            1. ðŸš€ Branch deploy your pull request to production

                > Comment \`.deploy\` on this pull request to trigger a deploy. If anything goes wrong, rollback with \`.deploy main\`

            1. ðŸŽ‰ Merge!
            `

            await github.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: commentBody
            })
